GET http://localhost:5000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdkZGNlNDg0NDg3MDBlMDNiODE0MyIsImlhdCI6MTYwODE1Mzg4NiwiZXhwIjoxNjA4MTU3NDg2fQ.xXPEq0AaLMuyBf6TptMydMeKwVSzjI8IyOIFQ8l8vLM

###Update Password
POST http://localhost:5000/auth/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdkZGNlNDg0NDg3MDBlMDNiODE0MyIsImlhdCI6MTYwODE1Mzg4NiwiZXhwIjoxNjA4MTU3NDg2fQ.xXPEq0AaLMuyBf6TptMydMeKwVSzjI8IyOIFQ8l8vLM

{
  "currentPassword": "qwerty",
  "newPassword": "123456"
}

###Update Details
PUT http://localhost:5000/auth/update-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdkZGNlNDg0NDg3MDBlMDNiODE0MyIsImlhdCI6MTYwODU4NTY3MiwiZXhwIjoxNjA4NTg5MjcyfQ.VBwksTcps18lWoYdswLreBoNt4IY1Y8FzTKaXnJBuD4

{
  "name": "Name Name",
  "email": "test@testx.com"
}


###Login Route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "test@testx.com",
  "password": "123456"
}
 
###Forgot Password Route
POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
  "email": "t.filiniuk@gmail.com"
}

###Register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "t.filiniuk@gmail.com",
  "password": "123456",
  "name": "Test"
}

###Refresh Token Route
POST http://localhost:5000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDdkZGNlNDg0NDg3MDBlMDNiODE0MyIsImlhdCI6MTYwNzk4MzEyMywiZXhwIjoxNjM5NTQwNzIzfQ.4E3cPl0I554hRj2hb64Y8sf_ior1qedjYojlEIJ0t6U"
}

###Logout Route
DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDczMzQxMTcsImV4cCI6MTYzODg5MTcxNywiYXVkIjoiNWZjZGVkMmQ0NGRlZjgzNjU4MTRhNjFlIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.89Q4iEZ-mDJXioQfYdZqN-fxnbkwiiJkUhdjkljQhoc"
}

